name: CICD Demo
on:
   pull_request:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout/@v4

         - names: Setup JDK 17
           uses: actions/setup-java@v4
           with:
              distribution: 'temurin'
              java-version: 17
              cache: 'gradle'

         - name: Grant execute permission for gradlew
           run: chmod +x gradlew

         - name: Run Unit test
           run: ./gradlew clean test Debug
